// Email TEMPLATE NAME
export const EMAIL_OTP_VERIFICATION = "EMAIL_OTP_VERIFICATION";
export const EMAIL_ACCOUNT_CREATED = "EMAIL_ACCOUNT_CREATED";
export const EMAIL_RESET_PASSWORD = "EMAIL_RESET_PASSWORD";
export const EMAIL_REQUEST_CUSTOM_PLAN = "EMAIL_REQUEST_CUSTOM_PLAN";
export const EMAIL_REPLY_CUSTOM_PLAN = "EMAIL_REPLY_CUSTOM_PLAN";
export const EMAIL_ADMIN_CUSTOM_MESSAGE = "EMAIL_ADMIN_CUSTOM_MESSAGE";
export const EMAIL_ACCOUNT_BLOCKED = "EMAIL_ACCOUNT_BLOCKED";
export const EMAIL_ACCOUNT_DEACTIVATED = "EMAIL_ACCOUNT_DEACTIVATED";

export const EMAIL_SUBSCRIPTION_CREATED = "EMAIL_SUBSCRIPTION_CREATED";
export const EMAIL_SUBSCRIPTION_CHARGED = "EMAIL_SUBSCRIPTION_CHARGED";
export const EMAIL_SUBSCRIPTION_PENDING = "EMAIL_SUBSCRIPTION_PENDING";
export const EMAIL_SUBSCRIPTION_HALTED = "EMAIL_SUBSCRIPTION_HALTED";
export const EMAIL_SUBSCRIPTION_CANCELLED = "EMAIL_SUBSCRIPTION_CANCELLED"
export const EMAIL_SUBSCRIPTION_PAUSED = "EMAIL_SUBSCRIPTION_PAUSED";
export const EMAIL_SUBSCRIPTION_RESUMED = "EMAIL_SUBSCRIPTION_RESUMED";
export const EMAIL_DONATE_CAPTURED = "EMAIL_DONATE_CAPTURED";
export const EMAIL_DONATE_FAILED = "EMAIL_DONATE_FAILED";