import mongoose from "mongoose";

const personalSchema = new mongoose.Schema(
    {
        name: {
            type: String,
            required: [true, "Please Enter Individual Name"],
        },
        mobileNumer: String,
        homeNumber: String,
        workNumber: String,
        otherNumber: String,
        personalEmail: String,
        workEmail: String,
        otherEmail: String,
        aboutMe: String,
        dateOfBirth: String,
        homeTown: String,
        currentCity: String,
        languages: String,
        music: String,
        color: String,
        city: String,
        travelDestination: String,
        season: String,
        uniqueSkills: String,
        cuisine: String,
        beverage: String,
        inspirationalQuotes: String,
        funnyQuotes: String,
        motivationalQuotes: String,
        otherQuotes: String,
        petLover: String,
        partyEnthusiast: String,
        smoker: String,
        maritalStatus: String,
        relationshipStatus: String,
        fitnessRoutine: String,
        morningPerson: String,
        diet: String,
        sleepingHabit: String,
        travelMode: String,
        genre: String,
        sports: String,
        artistisPursuits: String,
        gaming: String,
        collectignHobby: String, 
        coffee: String,
        cookingSkills: String,
        currentOcupation: String,
        careerAspiation: String,
        education: String,
        skills: String,
        travelMode_Other: String,
        genre_Other: String,
        sports_Other: String,
        artistisPursuits_Other: String,
        gaming_Other: String,
        collectignHobby_Other: String, 
        coffee_Other: String,
        cookingSkills_Other: String,
        currentOcupation_Other: String,
        careerAspiation_Other: String,
        education_Other: String,
        skills_Other: String,
        diet_Other: String,
        spiritual: String,
        core: String,
        philosophy: String,
        socialCause: String,
        globalIssues: String,
        weirdBelief: String,
        otherInterests: String,
        futureGoals: String,
        current: String,
        unusualExperinece: String,
        strangeHabits: String,
        socialMedia: [Object],
        user: {
            type: mongoose.Schema.ObjectId,
            ref: "User",
            required: true,
        }, 
    },
    {
        timestamps: true
    }
)

const Personal = mongoose.model("Personal", personalSchema);
export default Personal;