import mongoose from "mongoose";

const personalSchema = new mongoose.Schema(
    {
        name: String,
        mobileNumer: String,
        homeNumber: String,
        workNumber: String,
        otherNumber: String,
        personalEmail: String,
        workEmail: String,
        otherEmail: String,
        aboutMe: String,
        dateOfBirth: Date,
        homeTown: String,
        currentCity: String,
        languages: String,
        music: String,
        color: String,
        city: String,
        travelDestination: String,
        season: String,
        uniqueSkills: String,
        cuisine: String,
        beverage: String,
        inspirationalQuotes: String,
        funnyQuotes: String,
        motivationalQuotes: String,
        otherQuotes: String,
        travelMode: String,
        petLover: String,
        partyEnthusiast: String,
        smoker: String,
        maritalStatus: String,
        relationshipStatus: String,
        fitnessRoutine: String,
        morningPerson: String,
        diet: String,
        sleepingHabit: String,
        genre: String,
        sports: String,
        artistisPursuits: String,
        gaming: String,
        collectignHobby: String, 
        coffee: String,
        cookingSkills: String,
        spiritual: String,
        core: String,
        philosophy: String,
        socialCause: String,
        globalIssues: String,
        weirdBelief: String,
        currentOcupation: String,
        careerAspiation: String,
        education: String,
        skills: String,
        otherInterests: String,
        futureGoals: String,
        current: String,
        unusualExperinece: String,
        strangeHabits: String,
        socialMedia: [Object],
        user: {
            type: mongoose.Schema.ObjectId,
            ref: "User",
            required: true,
        }, 
    },
    {
        timestamps: true
    }
)

const Personal = mongoose.model("Personal", personalSchema);
export default Personal;